inversion=float(input("Introduce la cantidad a invertir: "))
interes_anual=float(input("Introduce el interes anual: "))
num_años=float(input("Introduce el numero de años: "))
capital=float(inversion*(1+interes_anual/100)**num_años)
print(f"Tu capital obtenido en tu inversion es de {capital}€")